parameters:
  pool: {}
jobs:
- job: Publish_Finalize
  condition: succeeded('Copy_Images')
  dependsOn:
  - Copy_Images
  pool: ${{ parameters.pool }}
  variables:
    imageBuilder.commonCmdArgs: >
      --manifest $(manifest)
      --registry-override $(acr.server)
      --repo-prefix $(publishRepoPrefix)
      $(imageBuilder.queueArgs)
  steps:
  - template: ../steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) publishManifest
      --username $(acr.userName)
      --password $(BotAccount-dotnet-docker-acr-bot-password)
      $(imageBuilder.commonCmdArgs)
    displayName: Publish Manifest
  # TODO:  Blocked on bot account
  # - script: >
  #     $(runImageBuilderCmd) publishMcrReadmes
  #     $(dotnetBuildBot-userName)
  #     $(dotnetBuildBot-email)
  #     $(AccessToken-dotnet-build-bot-public-repo)
  #     $(imageBuilder.commonCmdArgs)
  #   displayName: Publish Readme
  - template: ../steps/cleanup-docker-linux.yml
